SIRKA_OBRAZOVKY, VYSKA_OBRAZOVKY = 1800,900
FARBA_POZADIA = (30, 30, 30)
FARBA_POZADIA_SUFLIKA = (100, 100, 100)
MAX_VZDIALENOST_NA_ZAPASOVANIE = 20
DIELIK_ANCHOR_POSITION = 20 # ze kazdy obrazok mam posunut o tolkoto pixelov dolava a hore, aby bol spravne
POCET_RIADKOV_SUFLIKA = 2
MEDZERY_DIELIKOV_V_SUFLIKU = 40 #pixelov
VYSKA_ZACIATKU_SUFLIKU = 700
RYCHLOST_POSUVANIA_SUFLIKU = 70
RYCHLOST_ZOOMOVANIA = 1/10

POCET_DIELIKOV_NA_SIRKU_OBRAZKA = 4 # bude to stvorcovy obrazok, tolko isto aj na vysku teda
SIRKA_STRANY_DIELIKU_PRE_OBRAZOK = 250
SIRKA_STRANY_DIELIKU_NAOZAJ = 50
OBRAZOK_SCALE_OFFSET = SIRKA_STRANY_DIELIKU_NAOZAJ / SIRKA_STRANY_DIELIKU_PRE_OBRAZOK
DIELIK_ANCHOR_POSITION_OBRAZOK = int(DIELIK_ANCHOR_POSITION / OBRAZOK_SCALE_OFFSET)