SIRKA_OBRAZOVKY, VYSKA_OBRAZOVKY = 1800,900
FARBA_POZADIA = (30, 30, 30)
MAX_VZDIALENOST_NA_ZAPASOVANIE = 20
DIELIK_ANCHOR_POSITION = 70 # ze kazdy obrazok mam posunut o tolkoto pixelov dolava a hore, aby bol spravne
POCET_RIADKOV_SUFLIKA = 3
MEDZERY_DIELIKOV_V_SUFLIKU = 40 #pixelov
VYSKA_ZACIATKU_SUFLIKU = 500